using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Data;

namespace MC1
{
    public static class BayOverview_LoadBaysList
    {
        public static List<string> LoadList_BayPositions()
        {
            List<string> ListBayPostions = new List<string>();
            ListBayPostions.Add("LINE2_B_25");
            ListBayPostions.Add("LINE2_B_26");
            ListBayPostions.Add("LINE2_B_27");
            ListBayPostions.Add("LINE2_B_28");
            ListBayPostions.Add("LINE2_B_29");
            ListBayPostions.Add("LINE2_B_30");
            ListBayPostions.Add("LINE2_B_31");
            ListBayPostions.Add("LINE2_B_32");
            ListBayPostions.Add("LINE2_B_33");
            ListBayPostions.Add("LINE2_B_34");
            ListBayPostions.Add("LINE2_B_35");
            ListBayPostions.Add("LINE2_B_36");
            ListBayPostions.Add("LINE3_Lower_02");
            ListBayPostions.Add("LINE3_Lower_04");
            ListBayPostions.Add("LINE3_Lower_06");
            ListBayPostions.Add("LINE3_Lower_08");
            ListBayPostions.Add("LINE3_Lower_10");
            ListBayPostions.Add("LINE3_Lower_12");
            ListBayPostions.Add("LINE3_Lower_14");
            ListBayPostions.Add("LINE3_Lower_16");
            ListBayPostions.Add("LINE3_Lower_18");
            ListBayPostions.Add("LINE3_Lower_20");
            ListBayPostions.Add("LINE3_Lower_22");
            ListBayPostions.Add("LINE3_Lower_24");
            ListBayPostions.Add("LINE3_Lower_26");
            ListBayPostions.Add("LINE3_Lower_28");
            ListBayPostions.Add("LINE3_Lower_30");
            ListBayPostions.Add("LINE3_Lower_32");
            ListBayPostions.Add("LINE3_Lower_34");
            ListBayPostions.Add("LINE3_Lower_36");
            ListBayPostions.Add("LINE3_Lower_38");
            ListBayPostions.Add("LINE3_Lower_40");
            ListBayPostions.Add("LINE3_Lower_42");
            ListBayPostions.Add("LINE3_Lower_44");
            ListBayPostions.Add("LINE3_Lower_46");
            ListBayPostions.Add("LINE3_Lower_48");
            ListBayPostions.Add("LINE3_Lower_50");
            ListBayPostions.Add("LINE3_Lower_52");
            ListBayPostions.Add("LINE3_Lower_54");
            ListBayPostions.Add("LINE3_Lower_56");
            ListBayPostions.Add("LINE3_Lower_58");
            ListBayPostions.Add("LINE3_Lower_60");
            ListBayPostions.Add("LINE3_Lower_62");
            ListBayPostions.Add("LINE3_Lower_64");
            ListBayPostions.Add("LINE3_Lower_66");
            ListBayPostions.Add("LINE3_Lower_68");
            ListBayPostions.Add("LINE3_Lower_70");
            ListBayPostions.Add("LINE3_Lower_72");
            ListBayPostions.Add("LINE3_Upper_01");
            ListBayPostions.Add("LINE3_Upper_03");
            ListBayPostions.Add("LINE3_Upper_05");
            ListBayPostions.Add("LINE3_Upper_07");
            ListBayPostions.Add("LINE3_Upper_09");
            ListBayPostions.Add("LINE3_Upper_11");
            ListBayPostions.Add("LINE3_Upper_13");
            ListBayPostions.Add("LINE3_Upper_15");
            ListBayPostions.Add("LINE3_Upper_17");
            ListBayPostions.Add("LINE3_Upper_19");
            ListBayPostions.Add("LINE3_Upper_21");
            ListBayPostions.Add("LINE3_Upper_23");
            ListBayPostions.Add("LINE3_Upper_25");
            ListBayPostions.Add("LINE3_Upper_27");
            ListBayPostions.Add("LINE3_Upper_29");
            ListBayPostions.Add("LINE3_Upper_31");
            ListBayPostions.Add("LINE3_Upper_33");
            ListBayPostions.Add("LINE3_Upper_35");
            ListBayPostions.Add("LINE3_Upper_37");
            ListBayPostions.Add("LINE3_Upper_39");
            ListBayPostions.Add("LINE3_Upper_41");
            ListBayPostions.Add("LINE3_Upper_43");
            ListBayPostions.Add("LINE3_Upper_45");
            ListBayPostions.Add("LINE3_Upper_47");
            ListBayPostions.Add("LINE3_Upper_49");
            ListBayPostions.Add("LINE3_Upper_51");
            ListBayPostions.Add("LINE3_Upper_53");
            ListBayPostions.Add("LINE3_Upper_55");
            ListBayPostions.Add("LINE3_Upper_57");
            ListBayPostions.Add("LINE3_Upper_59");
            ListBayPostions.Add("LINE3_Upper_61");
            ListBayPostions.Add("LINE3_Upper_63");
            ListBayPostions.Add("LINE3_Upper_65");
            ListBayPostions.Add("LINE3_Upper_67");
            ListBayPostions.Add("LINE3_Upper_69");
            ListBayPostions.Add("LINE3_Upper_71");
            ListBayPostions.Add("LINE4_Lower_02");
            ListBayPostions.Add("LINE4_Lower_04");
            ListBayPostions.Add("LINE4_Lower_06");
            ListBayPostions.Add("LINE4_Lower_08");
            ListBayPostions.Add("LINE4_Lower_10");
            ListBayPostions.Add("LINE4_Lower_12");
            ListBayPostions.Add("LINE4_Lower_14");
            ListBayPostions.Add("LINE4_Lower_16");
            ListBayPostions.Add("LINE4_Lower_18");
            ListBayPostions.Add("LINE4_Lower_20");
            ListBayPostions.Add("LINE4_Lower_22");
            ListBayPostions.Add("LINE4_Lower_24");
            ListBayPostions.Add("LINE4_Lower_26");
            ListBayPostions.Add("LINE4_Lower_28");
            ListBayPostions.Add("LINE4_Lower_30");
            ListBayPostions.Add("LINE4_Lower_32");
            ListBayPostions.Add("LINE4_Lower_34");
            ListBayPostions.Add("LINE4_Lower_36");
            ListBayPostions.Add("LINE4_Lower_38");
            ListBayPostions.Add("LINE4_Lower_40");
            ListBayPostions.Add("LINE4_Lower_42");
            ListBayPostions.Add("LINE4_Lower_44");
            ListBayPostions.Add("LINE4_Lower_46");
            ListBayPostions.Add("LINE4_Lower_48");
            ListBayPostions.Add("LINE4_Lower_50");
            ListBayPostions.Add("LINE4_Lower_52");
            ListBayPostions.Add("LINE4_Lower_54");
            ListBayPostions.Add("LINE4_Lower_56");
            ListBayPostions.Add("LINE4_Lower_58");
            ListBayPostions.Add("LINE4_Lower_60");
            ListBayPostions.Add("LINE4_Lower_62");
            ListBayPostions.Add("LINE4_Lower_64");
            ListBayPostions.Add("LINE4_Lower_66");
            ListBayPostions.Add("LINE4_Lower_68");
            ListBayPostions.Add("LINE4_Lower_70");
            ListBayPostions.Add("LINE4_Lower_72");
            ListBayPostions.Add("LINE4_Upper_01");
            ListBayPostions.Add("LINE4_Upper_03");
            ListBayPostions.Add("LINE4_Upper_05");
            ListBayPostions.Add("LINE4_Upper_07");
            ListBayPostions.Add("LINE4_Upper_09");
            ListBayPostions.Add("LINE4_Upper_11");
            ListBayPostions.Add("LINE4_Upper_13");
            ListBayPostions.Add("LINE4_Upper_15");
            ListBayPostions.Add("LINE4_Upper_17");
            ListBayPostions.Add("LINE4_Upper_19");
            ListBayPostions.Add("LINE4_Upper_21");
            ListBayPostions.Add("LINE4_Upper_23");
            ListBayPostions.Add("LINE4_Upper_25");
            ListBayPostions.Add("LINE4_Upper_27");
            ListBayPostions.Add("LINE4_Upper_29");
            ListBayPostions.Add("LINE4_Upper_31");
            ListBayPostions.Add("LINE4_Upper_33");
            ListBayPostions.Add("LINE4_Upper_35");
            ListBayPostions.Add("LINE4_Upper_37");
            ListBayPostions.Add("LINE4_Upper_39");
            ListBayPostions.Add("LINE4_Upper_41");
            ListBayPostions.Add("LINE4_Upper_43");
            ListBayPostions.Add("LINE4_Upper_45");
            ListBayPostions.Add("LINE4_Upper_47");
            ListBayPostions.Add("LINE4_Upper_49");
            ListBayPostions.Add("LINE4_Upper_51");
            ListBayPostions.Add("LINE4_Upper_53");
            ListBayPostions.Add("LINE4_Upper_55");
            ListBayPostions.Add("LINE4_Upper_57");
            ListBayPostions.Add("LINE4_Upper_59");
            ListBayPostions.Add("LINE4_Upper_61");
            ListBayPostions.Add("LINE4_Upper_63");
            ListBayPostions.Add("LINE4_Upper_65");
            ListBayPostions.Add("LINE4_Upper_67");
            ListBayPostions.Add("LINE4_Upper_69");
            ListBayPostions.Add("LINE4_Upper_71");
            ListBayPostions.Add("LINE5_Lower_02");
            ListBayPostions.Add("LINE5_Lower_04");
            ListBayPostions.Add("LINE5_Lower_06");
            ListBayPostions.Add("LINE5_Lower_08");
            ListBayPostions.Add("LINE5_Lower_10");
            ListBayPostions.Add("LINE5_Lower_12");
            ListBayPostions.Add("LINE5_Lower_14");
            ListBayPostions.Add("LINE5_Lower_16");
            ListBayPostions.Add("LINE5_Lower_18");
            ListBayPostions.Add("LINE5_Lower_20");
            ListBayPostions.Add("LINE5_Lower_22");
            ListBayPostions.Add("LINE5_Lower_24");
            ListBayPostions.Add("LINE5_Lower_26");
            ListBayPostions.Add("LINE5_Lower_28");
            ListBayPostions.Add("LINE5_Lower_30");
            ListBayPostions.Add("LINE5_Lower_32");
            ListBayPostions.Add("LINE5_Lower_34");
            ListBayPostions.Add("LINE5_Lower_36");
            ListBayPostions.Add("LINE5_Lower_38");
            ListBayPostions.Add("LINE5_Lower_40");
            ListBayPostions.Add("LINE5_Lower_42");
            ListBayPostions.Add("LINE5_Lower_44");
            ListBayPostions.Add("LINE5_Lower_46");
            ListBayPostions.Add("LINE5_Lower_48");
            ListBayPostions.Add("LINE5_Lower_50");
            ListBayPostions.Add("LINE5_Lower_52");
            ListBayPostions.Add("LINE5_Lower_54");
            ListBayPostions.Add("LINE5_Lower_56");
            ListBayPostions.Add("LINE5_Lower_58");
            ListBayPostions.Add("LINE5_Lower_60");
            ListBayPostions.Add("LINE5_Lower_62");
            ListBayPostions.Add("LINE5_Lower_64");
            ListBayPostions.Add("LINE5_Lower_66");
            ListBayPostions.Add("LINE5_Lower_68");
            ListBayPostions.Add("LINE5_Lower_70");
            ListBayPostions.Add("LINE5_Lower_72");
            ListBayPostions.Add("LINE5_Lower_74");
            ListBayPostions.Add("LINE5_Lower_76");
            ListBayPostions.Add("LINE5_Lower_78");
            ListBayPostions.Add("LINE5_Lower_80");
            ListBayPostions.Add("LINE5_Upper_01");
            ListBayPostions.Add("LINE5_Upper_03");
            ListBayPostions.Add("LINE5_Upper_05");
            ListBayPostions.Add("LINE5_Upper_07");
            ListBayPostions.Add("LINE5_Upper_09");
            ListBayPostions.Add("LINE5_Upper_11");
            ListBayPostions.Add("LINE5_Upper_13");
            ListBayPostions.Add("LINE5_Upper_15");
            ListBayPostions.Add("LINE5_Upper_17");
            ListBayPostions.Add("LINE5_Upper_19");
            ListBayPostions.Add("LINE5_Upper_21");
            ListBayPostions.Add("LINE5_Upper_23");
            ListBayPostions.Add("LINE5_Upper_25");
            ListBayPostions.Add("LINE5_Upper_27");
            ListBayPostions.Add("LINE5_Upper_29");
            ListBayPostions.Add("LINE5_Upper_31");
            ListBayPostions.Add("LINE5_Upper_33");
            ListBayPostions.Add("LINE5_Upper_35");
            ListBayPostions.Add("LINE5_Upper_37");
            ListBayPostions.Add("LINE5_Upper_39");
            ListBayPostions.Add("LINE5_Upper_41");
            ListBayPostions.Add("LINE5_Upper_43");
            ListBayPostions.Add("LINE5_Upper_45");
            ListBayPostions.Add("LINE5_Upper_47");
            ListBayPostions.Add("LINE5_Upper_49");
            ListBayPostions.Add("LINE5_Upper_51");
            ListBayPostions.Add("LINE5_Upper_53");
            ListBayPostions.Add("LINE5_Upper_55");
            ListBayPostions.Add("LINE5_Upper_57");
            ListBayPostions.Add("LINE5_Upper_59");
            ListBayPostions.Add("LINE5_Upper_61");
            ListBayPostions.Add("LINE5_Upper_63");
            ListBayPostions.Add("LINE5_Upper_65");
            ListBayPostions.Add("LINE5_Upper_67");
            ListBayPostions.Add("LINE5_Upper_69");
            ListBayPostions.Add("LINE5_Upper_71");
            ListBayPostions.Add("LINE5_Upper_73");
            ListBayPostions.Add("LINE5_Upper_75");
            ListBayPostions.Add("LINE5_Upper_77");
            ListBayPostions.Add("LINE5_Upper_79");
            ListBayPostions.Add("LINE6_Lower_02");
            ListBayPostions.Add("LINE6_Lower_04");
            ListBayPostions.Add("LINE6_Lower_06");
            ListBayPostions.Add("LINE6_Lower_08");
            ListBayPostions.Add("LINE6_Lower_10");
            ListBayPostions.Add("LINE6_Lower_12");
            ListBayPostions.Add("LINE6_Lower_14");
            ListBayPostions.Add("LINE6_Lower_16");
            ListBayPostions.Add("LINE6_Lower_18");
            ListBayPostions.Add("LINE6_Lower_20");
            ListBayPostions.Add("LINE6_Lower_22");
            ListBayPostions.Add("LINE6_Lower_24");
            ListBayPostions.Add("LINE6_Lower_26");
            ListBayPostions.Add("LINE6_Lower_28");
            ListBayPostions.Add("LINE6_Lower_30");
            ListBayPostions.Add("LINE6_Lower_32");
            ListBayPostions.Add("LINE6_Lower_34");
            ListBayPostions.Add("LINE6_Lower_36");
            ListBayPostions.Add("LINE6_Lower_38");
            ListBayPostions.Add("LINE6_Lower_40");
            ListBayPostions.Add("LINE6_Upper_01");
            ListBayPostions.Add("LINE6_Upper_03");
            ListBayPostions.Add("LINE6_Upper_05");
            ListBayPostions.Add("LINE6_Upper_07");
            ListBayPostions.Add("LINE6_Upper_09");
            ListBayPostions.Add("LINE6_Upper_11");
            ListBayPostions.Add("LINE6_Upper_13");
            ListBayPostions.Add("LINE6_Upper_15");
            ListBayPostions.Add("LINE6_Upper_17");
            ListBayPostions.Add("LINE6_Upper_19");
            ListBayPostions.Add("LINE6_Upper_21");
            ListBayPostions.Add("LINE6_Upper_23");
            ListBayPostions.Add("LINE6_Upper_25");
            ListBayPostions.Add("LINE6_Upper_27");
            ListBayPostions.Add("LINE6_Upper_29");
            ListBayPostions.Add("LINE6_Upper_31");
            ListBayPostions.Add("LINE6_Upper_33");
            ListBayPostions.Add("LINE6_Upper_35");
            ListBayPostions.Add("LINE6_Upper_37");
            ListBayPostions.Add("LINE6_Upper_39");
            ListBayPostions.Add("LINE7_Lower_02");
            ListBayPostions.Add("LINE7_Lower_04");
            ListBayPostions.Add("LINE7_Lower_06");
            ListBayPostions.Add("LINE7_Lower_08");
            ListBayPostions.Add("LINE7_Lower_10");
            ListBayPostions.Add("LINE7_Lower_12");
            ListBayPostions.Add("LINE7_Lower_14");
            ListBayPostions.Add("LINE7_Lower_16");
            ListBayPostions.Add("LINE7_Lower_18");
            ListBayPostions.Add("LINE7_Lower_20");
            ListBayPostions.Add("LINE7_Lower_22");
            ListBayPostions.Add("LINE7_Lower_24");
            ListBayPostions.Add("LINE7_Lower_26");
            ListBayPostions.Add("LINE7_Lower_28");
            ListBayPostions.Add("LINE7_Lower_30");
            ListBayPostions.Add("LINE7_Lower_32");
            ListBayPostions.Add("LINE7_Lower_34");
            ListBayPostions.Add("LINE7_Lower_36");
            ListBayPostions.Add("LINE7_Lower_38");
            ListBayPostions.Add("LINE7_Lower_40");
            ListBayPostions.Add("LINE7_Lower_50");
            ListBayPostions.Add("LINE7_Lower_52");
            ListBayPostions.Add("LINE7_Lower_54");
            ListBayPostions.Add("LINE7_Lower_56");
            ListBayPostions.Add("LINE7_Lower_58");
            ListBayPostions.Add("LINE7_Lower_60");
            ListBayPostions.Add("LINE7_Lower_62");
            ListBayPostions.Add("LINE7_Lower_64");
            ListBayPostions.Add("LINE7_Lower_66");
            ListBayPostions.Add("LINE7_Lower_68");
            ListBayPostions.Add("LINE7_Lower_70");
            ListBayPostions.Add("LINE7_Lower_72");
            ListBayPostions.Add("LINE7_Upper_01");
            ListBayPostions.Add("LINE7_Upper_03");
            ListBayPostions.Add("LINE7_Upper_05");
            ListBayPostions.Add("LINE7_Upper_07");
            ListBayPostions.Add("LINE7_Upper_09");
            ListBayPostions.Add("LINE7_Upper_11");
            ListBayPostions.Add("LINE7_Upper_13");
            ListBayPostions.Add("LINE7_Upper_15");
            ListBayPostions.Add("LINE7_Upper_17");
            ListBayPostions.Add("LINE7_Upper_19");
            ListBayPostions.Add("LINE7_Upper_21");
            ListBayPostions.Add("LINE7_Upper_23");
            ListBayPostions.Add("LINE7_Upper_25");
            ListBayPostions.Add("LINE7_Upper_27");
            ListBayPostions.Add("LINE7_Upper_29");
            ListBayPostions.Add("LINE7_Upper_31");
            ListBayPostions.Add("LINE7_Upper_33");
            ListBayPostions.Add("LINE7_Upper_35");
            ListBayPostions.Add("LINE7_Upper_37");
            ListBayPostions.Add("LINE7_Upper_39");
            ListBayPostions.Add("LINE7_Upper_49");
            ListBayPostions.Add("LINE7_Upper_51");
            ListBayPostions.Add("LINE7_Upper_53");
            ListBayPostions.Add("LINE7_Upper_55");
            ListBayPostions.Add("LINE7_Upper_57");
            ListBayPostions.Add("LINE7_Upper_59");
            ListBayPostions.Add("LINE7_Upper_61");
            ListBayPostions.Add("LINE7_Upper_63");
            ListBayPostions.Add("LINE7_Upper_65");
            ListBayPostions.Add("LINE7_Upper_67");
            ListBayPostions.Add("LINE7_Upper_69");
            ListBayPostions.Add("LINE7_Upper_71");
            ListBayPostions.Add("LINE8_Lower_02");
            ListBayPostions.Add("LINE8_Lower_04");
            ListBayPostions.Add("LINE8_Lower_06");
            ListBayPostions.Add("LINE8_Lower_08");
            ListBayPostions.Add("LINE8_Lower_10");
            ListBayPostions.Add("LINE8_Lower_12");
            ListBayPostions.Add("LINE8_Lower_14");
            ListBayPostions.Add("LINE8_Lower_16");
            ListBayPostions.Add("LINE8_Lower_18");
            ListBayPostions.Add("LINE8_Lower_20");
            ListBayPostions.Add("LINE8_Lower_22");
            ListBayPostions.Add("LINE8_Lower_24");
            ListBayPostions.Add("LINE8_Lower_26");
            ListBayPostions.Add("LINE8_Lower_28");
            ListBayPostions.Add("LINE8_Lower_30");
            ListBayPostions.Add("LINE8_Lower_32");
            ListBayPostions.Add("LINE8_Lower_34");
            ListBayPostions.Add("LINE8_Lower_36");
            ListBayPostions.Add("LINE8_Lower_38");
            ListBayPostions.Add("LINE8_Lower_40");
            ListBayPostions.Add("LINE8_Lower_50");
            ListBayPostions.Add("LINE8_Lower_52");
            ListBayPostions.Add("LINE8_Lower_54");
            ListBayPostions.Add("LINE8_Lower_56");
            ListBayPostions.Add("LINE8_Lower_58");
            ListBayPostions.Add("LINE8_Lower_60");
            ListBayPostions.Add("LINE8_Lower_62");
            ListBayPostions.Add("LINE8_Lower_64");
            ListBayPostions.Add("LINE8_Lower_66");
            ListBayPostions.Add("LINE8_Lower_68");
            ListBayPostions.Add("LINE8_Lower_70");
            ListBayPostions.Add("LINE8_Lower_72");
            ListBayPostions.Add("LINE8_Upper_01");
            ListBayPostions.Add("LINE8_Upper_03");
            ListBayPostions.Add("LINE8_Upper_05");
            ListBayPostions.Add("LINE8_Upper_07");
            ListBayPostions.Add("LINE8_Upper_09");
            ListBayPostions.Add("LINE8_Upper_11");
            ListBayPostions.Add("LINE8_Upper_13");
            ListBayPostions.Add("LINE8_Upper_15");
            ListBayPostions.Add("LINE8_Upper_17");
            ListBayPostions.Add("LINE8_Upper_19");
            ListBayPostions.Add("LINE8_Upper_21");
            ListBayPostions.Add("LINE8_Upper_23");
            ListBayPostions.Add("LINE8_Upper_25");
            ListBayPostions.Add("LINE8_Upper_27");
            ListBayPostions.Add("LINE8_Upper_29");
            ListBayPostions.Add("LINE8_Upper_31");
            ListBayPostions.Add("LINE8_Upper_33");
            ListBayPostions.Add("LINE8_Upper_35");
            ListBayPostions.Add("LINE8_Upper_37");
            ListBayPostions.Add("LINE8_Upper_39");
            ListBayPostions.Add("LINE8_Upper_49");
            ListBayPostions.Add("LINE8_Upper_51");
            ListBayPostions.Add("LINE8_Upper_53");
            ListBayPostions.Add("LINE8_Upper_55");
            ListBayPostions.Add("LINE8_Upper_57");
            ListBayPostions.Add("LINE8_Upper_59");
            ListBayPostions.Add("LINE8_Upper_61");
            ListBayPostions.Add("LINE8_Upper_63");
            ListBayPostions.Add("LINE8_Upper_65");
            ListBayPostions.Add("LINE8_Upper_67");
            ListBayPostions.Add("LINE8_Upper_69");
            ListBayPostions.Add("LINE8_Upper_71");
            ListBayPostions.Add("LINEDMR_Lower_02");
            ListBayPostions.Add("LINEDMR_Lower_04");
            ListBayPostions.Add("LINEDMR_Lower_06");
            ListBayPostions.Add("LINEDMR_Lower_08");
            ListBayPostions.Add("LINEDMR_Lower_10");
            ListBayPostions.Add("LINEDMR_Lower_12");
            ListBayPostions.Add("LINEDMR_Lower_14");
            ListBayPostions.Add("LINEDMR_Lower_16");
            ListBayPostions.Add("LINEDMR_Upper_01");
            ListBayPostions.Add("LINEDMR_Upper_03");
            ListBayPostions.Add("LINEDMR_Upper_05");
            ListBayPostions.Add("LINEDMR_Upper_07");
            ListBayPostions.Add("LINEOBA_Lower_02");
            ListBayPostions.Add("LINEOBA_Lower_04");
            ListBayPostions.Add("LINEOBA_Lower_06");
            ListBayPostions.Add("LINEOBA_Lower_08");
            ListBayPostions.Add("LINEOBA_Lower_10");
            ListBayPostions.Add("LINEOBA_Lower_12");
            ListBayPostions.Add("LINEOBA_Lower_14");
            ListBayPostions.Add("LINEOBA_Lower_16");
            ListBayPostions.Add("LINEOBA_Upper_01");
            ListBayPostions.Add("LINEOBA_Upper_03");
            ListBayPostions.Add("LINEOBA_Upper_05");
            ListBayPostions.Add("LINEOBA_Upper_07");
            ListBayPostions.Add("LINEOBA_Upper_09");
            ListBayPostions.Add("LINEOBA_Upper_11");
            ListBayPostions.Add("LINEOBA_Upper_13");
            ListBayPostions.Add("LINEOBA_Upper_15");
            ListBayPostions.Add("LINEPRI_Lower_10");
            ListBayPostions.Add("LINEPRI_Lower_12");
            ListBayPostions.Add("LINEPRI_Lower_14");
            ListBayPostions.Add("LINEPRI_Lower_16");
            ListBayPostions.Add("LINEPRI_Lower_18");
            ListBayPostions.Add("LINEPRI_Lower_20");
            ListBayPostions.Add("LINEPRI_Lower_22");
            ListBayPostions.Add("LINEPRI_Lower_24");
            ListBayPostions.Add("LINEPRI_Upper_09");
            ListBayPostions.Add("LINEPRI_Upper_11");
            ListBayPostions.Add("LINEPRI_Upper_13");
            ListBayPostions.Add("LINEPRI_Upper_15");
            ListBayPostions.Add("LINEPRI_Upper_17");
            ListBayPostions.Add("LINEPRI_Upper_19");
            ListBayPostions.Add("LINEPRI_Upper_21");
            ListBayPostions.Add("LINEPRI_Upper_23");
            return ListBayPostions;
        }

        public static Dictionary<string, string> LoadDict_BayPositions()
        {
            Dictionary<string, string> DictionaryBaysOccupation = new Dictionary<string, string>();

            DictionaryBaysOccupation.Add("LINE2_B_25", "0");
            DictionaryBaysOccupation.Add("LINE2_B_26", "0");
            DictionaryBaysOccupation.Add("LINE2_B_27", "0");
            DictionaryBaysOccupation.Add("LINE2_B_28", "0");
            DictionaryBaysOccupation.Add("LINE2_B_29", "0");
            DictionaryBaysOccupation.Add("LINE2_B_30", "0");
            DictionaryBaysOccupation.Add("LINE2_B_31", "0");
            DictionaryBaysOccupation.Add("LINE2_B_32", "0");
            DictionaryBaysOccupation.Add("LINE2_B_33", "0");
            DictionaryBaysOccupation.Add("LINE2_B_34", "0");
            DictionaryBaysOccupation.Add("LINE2_B_35", "0");
            DictionaryBaysOccupation.Add("LINE2_B_36", "0");
            DictionaryBaysOccupation.Add("LINE3_Lower_02", "0");
            DictionaryBaysOccupation.Add("LINE3_Lower_04", "0");
            DictionaryBaysOccupation.Add("LINE3_Lower_06", "0");
            DictionaryBaysOccupation.Add("LINE3_Lower_08", "0");
            DictionaryBaysOccupation.Add("LINE3_Lower_10", "0");
            DictionaryBaysOccupation.Add("LINE3_Lower_12", "0");
            DictionaryBaysOccupation.Add("LINE3_Lower_14", "0");
            DictionaryBaysOccupation.Add("LINE3_Lower_16", "0");
            DictionaryBaysOccupation.Add("LINE3_Lower_18", "0");
            DictionaryBaysOccupation.Add("LINE3_Lower_20", "0");
            DictionaryBaysOccupation.Add("LINE3_Lower_22", "0");
            DictionaryBaysOccupation.Add("LINE3_Lower_24", "0");
            DictionaryBaysOccupation.Add("LINE3_Lower_26", "0");
            DictionaryBaysOccupation.Add("LINE3_Lower_28", "0");
            DictionaryBaysOccupation.Add("LINE3_Lower_30", "0");
            DictionaryBaysOccupation.Add("LINE3_Lower_32", "0");
            DictionaryBaysOccupation.Add("LINE3_Lower_34", "0");
            DictionaryBaysOccupation.Add("LINE3_Lower_36", "0");
            DictionaryBaysOccupation.Add("LINE3_Lower_38", "0");
            DictionaryBaysOccupation.Add("LINE3_Lower_40", "0");
            DictionaryBaysOccupation.Add("LINE3_Lower_42", "0");
            DictionaryBaysOccupation.Add("LINE3_Lower_44", "0");
            DictionaryBaysOccupation.Add("LINE3_Lower_46", "0");
            DictionaryBaysOccupation.Add("LINE3_Lower_48", "0");
            DictionaryBaysOccupation.Add("LINE3_Lower_50", "0");
            DictionaryBaysOccupation.Add("LINE3_Lower_52", "0");
            DictionaryBaysOccupation.Add("LINE3_Lower_54", "0");
            DictionaryBaysOccupation.Add("LINE3_Lower_56", "0");
            DictionaryBaysOccupation.Add("LINE3_Lower_58", "0");
            DictionaryBaysOccupation.Add("LINE3_Lower_60", "0");
            DictionaryBaysOccupation.Add("LINE3_Lower_62", "0");
            DictionaryBaysOccupation.Add("LINE3_Lower_64", "0");
            DictionaryBaysOccupation.Add("LINE3_Lower_66", "0");
            DictionaryBaysOccupation.Add("LINE3_Lower_68", "0");
            DictionaryBaysOccupation.Add("LINE3_Lower_70", "0");
            DictionaryBaysOccupation.Add("LINE3_Lower_72", "0");
            DictionaryBaysOccupation.Add("LINE3_Upper_01", "0");
            DictionaryBaysOccupation.Add("LINE3_Upper_03", "0");
            DictionaryBaysOccupation.Add("LINE3_Upper_05", "0");
            DictionaryBaysOccupation.Add("LINE3_Upper_07", "0");
            DictionaryBaysOccupation.Add("LINE3_Upper_09", "0");
            DictionaryBaysOccupation.Add("LINE3_Upper_11", "0");
            DictionaryBaysOccupation.Add("LINE3_Upper_13", "0");
            DictionaryBaysOccupation.Add("LINE3_Upper_15", "0");
            DictionaryBaysOccupation.Add("LINE3_Upper_17", "0");
            DictionaryBaysOccupation.Add("LINE3_Upper_19", "0");
            DictionaryBaysOccupation.Add("LINE3_Upper_21", "0");
            DictionaryBaysOccupation.Add("LINE3_Upper_23", "0");
            DictionaryBaysOccupation.Add("LINE3_Upper_25", "0");
            DictionaryBaysOccupation.Add("LINE3_Upper_27", "0");
            DictionaryBaysOccupation.Add("LINE3_Upper_29", "0");
            DictionaryBaysOccupation.Add("LINE3_Upper_31", "0");
            DictionaryBaysOccupation.Add("LINE3_Upper_33", "0");
            DictionaryBaysOccupation.Add("LINE3_Upper_35", "0");
            DictionaryBaysOccupation.Add("LINE3_Upper_37", "0");
            DictionaryBaysOccupation.Add("LINE3_Upper_39", "0");
            DictionaryBaysOccupation.Add("LINE3_Upper_41", "0");
            DictionaryBaysOccupation.Add("LINE3_Upper_43", "0");
            DictionaryBaysOccupation.Add("LINE3_Upper_45", "0");
            DictionaryBaysOccupation.Add("LINE3_Upper_47", "0");
            DictionaryBaysOccupation.Add("LINE3_Upper_49", "0");
            DictionaryBaysOccupation.Add("LINE3_Upper_51", "0");
            DictionaryBaysOccupation.Add("LINE3_Upper_53", "0");
            DictionaryBaysOccupation.Add("LINE3_Upper_55", "0");
            DictionaryBaysOccupation.Add("LINE3_Upper_57", "0");
            DictionaryBaysOccupation.Add("LINE3_Upper_59", "0");
            DictionaryBaysOccupation.Add("LINE3_Upper_61", "0");
            DictionaryBaysOccupation.Add("LINE3_Upper_63", "0");
            DictionaryBaysOccupation.Add("LINE3_Upper_65", "0");
            DictionaryBaysOccupation.Add("LINE3_Upper_67", "0");
            DictionaryBaysOccupation.Add("LINE3_Upper_69", "0");
            DictionaryBaysOccupation.Add("LINE3_Upper_71", "0");
            DictionaryBaysOccupation.Add("LINE4_Lower_02", "0");
            DictionaryBaysOccupation.Add("LINE4_Lower_04", "0");
            DictionaryBaysOccupation.Add("LINE4_Lower_06", "0");
            DictionaryBaysOccupation.Add("LINE4_Lower_08", "0");
            DictionaryBaysOccupation.Add("LINE4_Lower_10", "0");
            DictionaryBaysOccupation.Add("LINE4_Lower_12", "0");
            DictionaryBaysOccupation.Add("LINE4_Lower_14", "0");
            DictionaryBaysOccupation.Add("LINE4_Lower_16", "0");
            DictionaryBaysOccupation.Add("LINE4_Lower_18", "0");
            DictionaryBaysOccupation.Add("LINE4_Lower_20", "0");
            DictionaryBaysOccupation.Add("LINE4_Lower_22", "0");
            DictionaryBaysOccupation.Add("LINE4_Lower_24", "0");
            DictionaryBaysOccupation.Add("LINE4_Lower_26", "0");
            DictionaryBaysOccupation.Add("LINE4_Lower_28", "0");
            DictionaryBaysOccupation.Add("LINE4_Lower_30", "0");
            DictionaryBaysOccupation.Add("LINE4_Lower_32", "0");
            DictionaryBaysOccupation.Add("LINE4_Lower_34", "0");
            DictionaryBaysOccupation.Add("LINE4_Lower_36", "0");
            DictionaryBaysOccupation.Add("LINE4_Lower_38", "0");
            DictionaryBaysOccupation.Add("LINE4_Lower_40", "0");
            DictionaryBaysOccupation.Add("LINE4_Lower_42", "0");
            DictionaryBaysOccupation.Add("LINE4_Lower_44", "0");
            DictionaryBaysOccupation.Add("LINE4_Lower_46", "0");
            DictionaryBaysOccupation.Add("LINE4_Lower_48", "0");
            DictionaryBaysOccupation.Add("LINE4_Lower_50", "0");
            DictionaryBaysOccupation.Add("LINE4_Lower_52", "0");
            DictionaryBaysOccupation.Add("LINE4_Lower_54", "0");
            DictionaryBaysOccupation.Add("LINE4_Lower_56", "0");
            DictionaryBaysOccupation.Add("LINE4_Lower_58", "0");
            DictionaryBaysOccupation.Add("LINE4_Lower_60", "0");
            DictionaryBaysOccupation.Add("LINE4_Lower_62", "0");
            DictionaryBaysOccupation.Add("LINE4_Lower_64", "0");
            DictionaryBaysOccupation.Add("LINE4_Lower_66", "0");
            DictionaryBaysOccupation.Add("LINE4_Lower_68", "0");
            DictionaryBaysOccupation.Add("LINE4_Lower_70", "0");
            DictionaryBaysOccupation.Add("LINE4_Lower_72", "0");
            DictionaryBaysOccupation.Add("LINE4_Upper_01", "0");
            DictionaryBaysOccupation.Add("LINE4_Upper_03", "0");
            DictionaryBaysOccupation.Add("LINE4_Upper_05", "0");
            DictionaryBaysOccupation.Add("LINE4_Upper_07", "0");
            DictionaryBaysOccupation.Add("LINE4_Upper_09", "0");
            DictionaryBaysOccupation.Add("LINE4_Upper_11", "0");
            DictionaryBaysOccupation.Add("LINE4_Upper_13", "0");
            DictionaryBaysOccupation.Add("LINE4_Upper_15", "0");
            DictionaryBaysOccupation.Add("LINE4_Upper_17", "0");
            DictionaryBaysOccupation.Add("LINE4_Upper_19", "0");
            DictionaryBaysOccupation.Add("LINE4_Upper_21", "0");
            DictionaryBaysOccupation.Add("LINE4_Upper_23", "0");
            DictionaryBaysOccupation.Add("LINE4_Upper_25", "0");
            DictionaryBaysOccupation.Add("LINE4_Upper_27", "0");
            DictionaryBaysOccupation.Add("LINE4_Upper_29", "0");
            DictionaryBaysOccupation.Add("LINE4_Upper_31", "0");
            DictionaryBaysOccupation.Add("LINE4_Upper_33", "0");
            DictionaryBaysOccupation.Add("LINE4_Upper_35", "0");
            DictionaryBaysOccupation.Add("LINE4_Upper_37", "0");
            DictionaryBaysOccupation.Add("LINE4_Upper_39", "0");
            DictionaryBaysOccupation.Add("LINE4_Upper_41", "0");
            DictionaryBaysOccupation.Add("LINE4_Upper_43", "0");
            DictionaryBaysOccupation.Add("LINE4_Upper_45", "0");
            DictionaryBaysOccupation.Add("LINE4_Upper_47", "0");
            DictionaryBaysOccupation.Add("LINE4_Upper_49", "0");
            DictionaryBaysOccupation.Add("LINE4_Upper_51", "0");
            DictionaryBaysOccupation.Add("LINE4_Upper_53", "0");
            DictionaryBaysOccupation.Add("LINE4_Upper_55", "0");
            DictionaryBaysOccupation.Add("LINE4_Upper_57", "0");
            DictionaryBaysOccupation.Add("LINE4_Upper_59", "0");
            DictionaryBaysOccupation.Add("LINE4_Upper_61", "0");
            DictionaryBaysOccupation.Add("LINE4_Upper_63", "0");
            DictionaryBaysOccupation.Add("LINE4_Upper_65", "0");
            DictionaryBaysOccupation.Add("LINE4_Upper_67", "0");
            DictionaryBaysOccupation.Add("LINE4_Upper_69", "0");
            DictionaryBaysOccupation.Add("LINE4_Upper_71", "0");
            DictionaryBaysOccupation.Add("LINE5_Lower_02", "0");
            DictionaryBaysOccupation.Add("LINE5_Lower_04", "0");
            DictionaryBaysOccupation.Add("LINE5_Lower_06", "0");
            DictionaryBaysOccupation.Add("LINE5_Lower_08", "0");
            DictionaryBaysOccupation.Add("LINE5_Lower_10", "0");
            DictionaryBaysOccupation.Add("LINE5_Lower_12", "0");
            DictionaryBaysOccupation.Add("LINE5_Lower_14", "0");
            DictionaryBaysOccupation.Add("LINE5_Lower_16", "0");
            DictionaryBaysOccupation.Add("LINE5_Lower_18", "0");
            DictionaryBaysOccupation.Add("LINE5_Lower_20", "0");
            DictionaryBaysOccupation.Add("LINE5_Lower_22", "0");
            DictionaryBaysOccupation.Add("LINE5_Lower_24", "0");
            DictionaryBaysOccupation.Add("LINE5_Lower_26", "0");
            DictionaryBaysOccupation.Add("LINE5_Lower_28", "0");
            DictionaryBaysOccupation.Add("LINE5_Lower_30", "0");
            DictionaryBaysOccupation.Add("LINE5_Lower_32", "0");
            DictionaryBaysOccupation.Add("LINE5_Lower_34", "0");
            DictionaryBaysOccupation.Add("LINE5_Lower_36", "0");
            DictionaryBaysOccupation.Add("LINE5_Lower_38", "0");
            DictionaryBaysOccupation.Add("LINE5_Lower_40", "0");
            DictionaryBaysOccupation.Add("LINE5_Lower_42", "0");
            DictionaryBaysOccupation.Add("LINE5_Lower_44", "0");
            DictionaryBaysOccupation.Add("LINE5_Lower_46", "0");
            DictionaryBaysOccupation.Add("LINE5_Lower_48", "0");
            DictionaryBaysOccupation.Add("LINE5_Lower_50", "0");
            DictionaryBaysOccupation.Add("LINE5_Lower_52", "0");
            DictionaryBaysOccupation.Add("LINE5_Lower_54", "0");
            DictionaryBaysOccupation.Add("LINE5_Lower_56", "0");
            DictionaryBaysOccupation.Add("LINE5_Lower_58", "0");
            DictionaryBaysOccupation.Add("LINE5_Lower_60", "0");
            DictionaryBaysOccupation.Add("LINE5_Lower_62", "0");
            DictionaryBaysOccupation.Add("LINE5_Lower_64", "0");
            DictionaryBaysOccupation.Add("LINE5_Lower_66", "0");
            DictionaryBaysOccupation.Add("LINE5_Lower_68", "0");
            DictionaryBaysOccupation.Add("LINE5_Lower_70", "0");
            DictionaryBaysOccupation.Add("LINE5_Lower_72", "0");
            DictionaryBaysOccupation.Add("LINE5_Lower_74", "0");
            DictionaryBaysOccupation.Add("LINE5_Lower_76", "0");
            DictionaryBaysOccupation.Add("LINE5_Lower_78", "0");
            DictionaryBaysOccupation.Add("LINE5_Lower_80", "0");
            DictionaryBaysOccupation.Add("LINE5_Upper_01", "0");
            DictionaryBaysOccupation.Add("LINE5_Upper_03", "0");
            DictionaryBaysOccupation.Add("LINE5_Upper_05", "0");
            DictionaryBaysOccupation.Add("LINE5_Upper_07", "0");
            DictionaryBaysOccupation.Add("LINE5_Upper_09", "0");
            DictionaryBaysOccupation.Add("LINE5_Upper_11", "0");
            DictionaryBaysOccupation.Add("LINE5_Upper_13", "0");
            DictionaryBaysOccupation.Add("LINE5_Upper_15", "0");
            DictionaryBaysOccupation.Add("LINE5_Upper_17", "0");
            DictionaryBaysOccupation.Add("LINE5_Upper_19", "0");
            DictionaryBaysOccupation.Add("LINE5_Upper_21", "0");
            DictionaryBaysOccupation.Add("LINE5_Upper_23", "0");
            DictionaryBaysOccupation.Add("LINE5_Upper_25", "0");
            DictionaryBaysOccupation.Add("LINE5_Upper_27", "0");
            DictionaryBaysOccupation.Add("LINE5_Upper_29", "0");
            DictionaryBaysOccupation.Add("LINE5_Upper_31", "0");
            DictionaryBaysOccupation.Add("LINE5_Upper_33", "0");
            DictionaryBaysOccupation.Add("LINE5_Upper_35", "0");
            DictionaryBaysOccupation.Add("LINE5_Upper_37", "0");
            DictionaryBaysOccupation.Add("LINE5_Upper_39", "0");
            DictionaryBaysOccupation.Add("LINE5_Upper_41", "0");
            DictionaryBaysOccupation.Add("LINE5_Upper_43", "0");
            DictionaryBaysOccupation.Add("LINE5_Upper_45", "0");
            DictionaryBaysOccupation.Add("LINE5_Upper_47", "0");
            DictionaryBaysOccupation.Add("LINE5_Upper_49", "0");
            DictionaryBaysOccupation.Add("LINE5_Upper_51", "0");
            DictionaryBaysOccupation.Add("LINE5_Upper_53", "0");
            DictionaryBaysOccupation.Add("LINE5_Upper_55", "0");
            DictionaryBaysOccupation.Add("LINE5_Upper_57", "0");
            DictionaryBaysOccupation.Add("LINE5_Upper_59", "0");
            DictionaryBaysOccupation.Add("LINE5_Upper_61", "0");
            DictionaryBaysOccupation.Add("LINE5_Upper_63", "0");
            DictionaryBaysOccupation.Add("LINE5_Upper_65", "0");
            DictionaryBaysOccupation.Add("LINE5_Upper_67", "0");
            DictionaryBaysOccupation.Add("LINE5_Upper_69", "0");
            DictionaryBaysOccupation.Add("LINE5_Upper_71", "0");
            DictionaryBaysOccupation.Add("LINE5_Upper_73", "0");
            DictionaryBaysOccupation.Add("LINE5_Upper_75", "0");
            DictionaryBaysOccupation.Add("LINE5_Upper_77", "0");
            DictionaryBaysOccupation.Add("LINE5_Upper_79", "0");
            DictionaryBaysOccupation.Add("LINE6_Lower_02", "0");
            DictionaryBaysOccupation.Add("LINE6_Lower_04", "0");
            DictionaryBaysOccupation.Add("LINE6_Lower_06", "0");
            DictionaryBaysOccupation.Add("LINE6_Lower_08", "0");
            DictionaryBaysOccupation.Add("LINE6_Lower_10", "0");
            DictionaryBaysOccupation.Add("LINE6_Lower_12", "0");
            DictionaryBaysOccupation.Add("LINE6_Lower_14", "0");
            DictionaryBaysOccupation.Add("LINE6_Lower_16", "0");
            DictionaryBaysOccupation.Add("LINE6_Lower_18", "0");
            DictionaryBaysOccupation.Add("LINE6_Lower_20", "0");
            DictionaryBaysOccupation.Add("LINE6_Lower_22", "0");
            DictionaryBaysOccupation.Add("LINE6_Lower_24", "0");
            DictionaryBaysOccupation.Add("LINE6_Lower_26", "0");
            DictionaryBaysOccupation.Add("LINE6_Lower_28", "0");
            DictionaryBaysOccupation.Add("LINE6_Lower_30", "0");
            DictionaryBaysOccupation.Add("LINE6_Lower_32", "0");
            DictionaryBaysOccupation.Add("LINE6_Lower_34", "0");
            DictionaryBaysOccupation.Add("LINE6_Lower_36", "0");
            DictionaryBaysOccupation.Add("LINE6_Lower_38", "0");
            DictionaryBaysOccupation.Add("LINE6_Lower_40", "0");
            DictionaryBaysOccupation.Add("LINE6_Upper_01", "0");
            DictionaryBaysOccupation.Add("LINE6_Upper_03", "0");
            DictionaryBaysOccupation.Add("LINE6_Upper_05", "0");
            DictionaryBaysOccupation.Add("LINE6_Upper_07", "0");
            DictionaryBaysOccupation.Add("LINE6_Upper_09", "0");
            DictionaryBaysOccupation.Add("LINE6_Upper_11", "0");
            DictionaryBaysOccupation.Add("LINE6_Upper_13", "0");
            DictionaryBaysOccupation.Add("LINE6_Upper_15", "0");
            DictionaryBaysOccupation.Add("LINE6_Upper_17", "0");
            DictionaryBaysOccupation.Add("LINE6_Upper_19", "0");
            DictionaryBaysOccupation.Add("LINE6_Upper_21", "0");
            DictionaryBaysOccupation.Add("LINE6_Upper_23", "0");
            DictionaryBaysOccupation.Add("LINE6_Upper_25", "0");
            DictionaryBaysOccupation.Add("LINE6_Upper_27", "0");
            DictionaryBaysOccupation.Add("LINE6_Upper_29", "0");
            DictionaryBaysOccupation.Add("LINE6_Upper_31", "0");
            DictionaryBaysOccupation.Add("LINE6_Upper_33", "0");
            DictionaryBaysOccupation.Add("LINE6_Upper_35", "0");
            DictionaryBaysOccupation.Add("LINE6_Upper_37", "0");
            DictionaryBaysOccupation.Add("LINE6_Upper_39", "0");
            DictionaryBaysOccupation.Add("LINE7_Lower_02", "0");
            DictionaryBaysOccupation.Add("LINE7_Lower_04", "0");
            DictionaryBaysOccupation.Add("LINE7_Lower_06", "0");
            DictionaryBaysOccupation.Add("LINE7_Lower_08", "0");
            DictionaryBaysOccupation.Add("LINE7_Lower_10", "0");
            DictionaryBaysOccupation.Add("LINE7_Lower_12", "0");
            DictionaryBaysOccupation.Add("LINE7_Lower_14", "0");
            DictionaryBaysOccupation.Add("LINE7_Lower_16", "0");
            DictionaryBaysOccupation.Add("LINE7_Lower_18", "0");
            DictionaryBaysOccupation.Add("LINE7_Lower_20", "0");
            DictionaryBaysOccupation.Add("LINE7_Lower_22", "0");
            DictionaryBaysOccupation.Add("LINE7_Lower_24", "0");
            DictionaryBaysOccupation.Add("LINE7_Lower_26", "0");
            DictionaryBaysOccupation.Add("LINE7_Lower_28", "0");
            DictionaryBaysOccupation.Add("LINE7_Lower_30", "0");
            DictionaryBaysOccupation.Add("LINE7_Lower_32", "0");
            DictionaryBaysOccupation.Add("LINE7_Lower_34", "0");
            DictionaryBaysOccupation.Add("LINE7_Lower_36", "0");
            DictionaryBaysOccupation.Add("LINE7_Lower_38", "0");
            DictionaryBaysOccupation.Add("LINE7_Lower_40", "0");
            DictionaryBaysOccupation.Add("LINE7_Lower_50", "0");
            DictionaryBaysOccupation.Add("LINE7_Lower_52", "0");
            DictionaryBaysOccupation.Add("LINE7_Lower_54", "0");
            DictionaryBaysOccupation.Add("LINE7_Lower_56", "0");
            DictionaryBaysOccupation.Add("LINE7_Lower_58", "0");
            DictionaryBaysOccupation.Add("LINE7_Lower_60", "0");
            DictionaryBaysOccupation.Add("LINE7_Lower_62", "0");
            DictionaryBaysOccupation.Add("LINE7_Lower_64", "0");
            DictionaryBaysOccupation.Add("LINE7_Lower_66", "0");
            DictionaryBaysOccupation.Add("LINE7_Lower_68", "0");
            DictionaryBaysOccupation.Add("LINE7_Lower_70", "0");
            DictionaryBaysOccupation.Add("LINE7_Lower_72", "0");
            DictionaryBaysOccupation.Add("LINE7_Upper_01", "0");
            DictionaryBaysOccupation.Add("LINE7_Upper_03", "0");
            DictionaryBaysOccupation.Add("LINE7_Upper_05", "0");
            DictionaryBaysOccupation.Add("LINE7_Upper_07", "0");
            DictionaryBaysOccupation.Add("LINE7_Upper_09", "0");
            DictionaryBaysOccupation.Add("LINE7_Upper_11", "0");
            DictionaryBaysOccupation.Add("LINE7_Upper_13", "0");
            DictionaryBaysOccupation.Add("LINE7_Upper_15", "0");
            DictionaryBaysOccupation.Add("LINE7_Upper_17", "0");
            DictionaryBaysOccupation.Add("LINE7_Upper_19", "0");
            DictionaryBaysOccupation.Add("LINE7_Upper_21", "0");
            DictionaryBaysOccupation.Add("LINE7_Upper_23", "0");
            DictionaryBaysOccupation.Add("LINE7_Upper_25", "0");
            DictionaryBaysOccupation.Add("LINE7_Upper_27", "0");
            DictionaryBaysOccupation.Add("LINE7_Upper_29", "0");
            DictionaryBaysOccupation.Add("LINE7_Upper_31", "0");
            DictionaryBaysOccupation.Add("LINE7_Upper_33", "0");
            DictionaryBaysOccupation.Add("LINE7_Upper_35", "0");
            DictionaryBaysOccupation.Add("LINE7_Upper_37", "0");
            DictionaryBaysOccupation.Add("LINE7_Upper_39", "0");
            DictionaryBaysOccupation.Add("LINE7_Upper_49", "0");
            DictionaryBaysOccupation.Add("LINE7_Upper_51", "0");
            DictionaryBaysOccupation.Add("LINE7_Upper_53", "0");
            DictionaryBaysOccupation.Add("LINE7_Upper_55", "0");
            DictionaryBaysOccupation.Add("LINE7_Upper_57", "0");
            DictionaryBaysOccupation.Add("LINE7_Upper_59", "0");
            DictionaryBaysOccupation.Add("LINE7_Upper_61", "0");
            DictionaryBaysOccupation.Add("LINE7_Upper_63", "0");
            DictionaryBaysOccupation.Add("LINE7_Upper_65", "0");
            DictionaryBaysOccupation.Add("LINE7_Upper_67", "0");
            DictionaryBaysOccupation.Add("LINE7_Upper_69", "0");
            DictionaryBaysOccupation.Add("LINE7_Upper_71", "0");
            DictionaryBaysOccupation.Add("LINE8_Lower_02", "0");
            DictionaryBaysOccupation.Add("LINE8_Lower_04", "0");
            DictionaryBaysOccupation.Add("LINE8_Lower_06", "0");
            DictionaryBaysOccupation.Add("LINE8_Lower_08", "0");
            DictionaryBaysOccupation.Add("LINE8_Lower_10", "0");
            DictionaryBaysOccupation.Add("LINE8_Lower_12", "0");
            DictionaryBaysOccupation.Add("LINE8_Lower_14", "0");
            DictionaryBaysOccupation.Add("LINE8_Lower_16", "0");
            DictionaryBaysOccupation.Add("LINE8_Lower_18", "0");
            DictionaryBaysOccupation.Add("LINE8_Lower_20", "0");
            DictionaryBaysOccupation.Add("LINE8_Lower_22", "0");
            DictionaryBaysOccupation.Add("LINE8_Lower_24", "0");
            DictionaryBaysOccupation.Add("LINE8_Lower_26", "0");
            DictionaryBaysOccupation.Add("LINE8_Lower_28", "0");
            DictionaryBaysOccupation.Add("LINE8_Lower_30", "0");
            DictionaryBaysOccupation.Add("LINE8_Lower_32", "0");
            DictionaryBaysOccupation.Add("LINE8_Lower_34", "0");
            DictionaryBaysOccupation.Add("LINE8_Lower_36", "0");
            DictionaryBaysOccupation.Add("LINE8_Lower_38", "0");
            DictionaryBaysOccupation.Add("LINE8_Lower_40", "0");
            DictionaryBaysOccupation.Add("LINE8_Lower_50", "0");
            DictionaryBaysOccupation.Add("LINE8_Lower_52", "0");
            DictionaryBaysOccupation.Add("LINE8_Lower_54", "0");
            DictionaryBaysOccupation.Add("LINE8_Lower_56", "0");
            DictionaryBaysOccupation.Add("LINE8_Lower_58", "0");
            DictionaryBaysOccupation.Add("LINE8_Lower_60", "0");
            DictionaryBaysOccupation.Add("LINE8_Lower_62", "0");
            DictionaryBaysOccupation.Add("LINE8_Lower_64", "0");
            DictionaryBaysOccupation.Add("LINE8_Lower_66", "0");
            DictionaryBaysOccupation.Add("LINE8_Lower_68", "0");
            DictionaryBaysOccupation.Add("LINE8_Lower_70", "0");
            DictionaryBaysOccupation.Add("LINE8_Lower_72", "0");
            DictionaryBaysOccupation.Add("LINE8_Upper_01", "0");
            DictionaryBaysOccupation.Add("LINE8_Upper_03", "0");
            DictionaryBaysOccupation.Add("LINE8_Upper_05", "0");
            DictionaryBaysOccupation.Add("LINE8_Upper_07", "0");
            DictionaryBaysOccupation.Add("LINE8_Upper_09", "0");
            DictionaryBaysOccupation.Add("LINE8_Upper_11", "0");
            DictionaryBaysOccupation.Add("LINE8_Upper_13", "0");
            DictionaryBaysOccupation.Add("LINE8_Upper_15", "0");
            DictionaryBaysOccupation.Add("LINE8_Upper_17", "0");
            DictionaryBaysOccupation.Add("LINE8_Upper_19", "0");
            DictionaryBaysOccupation.Add("LINE8_Upper_21", "0");
            DictionaryBaysOccupation.Add("LINE8_Upper_23", "0");
            DictionaryBaysOccupation.Add("LINE8_Upper_25", "0");
            DictionaryBaysOccupation.Add("LINE8_Upper_27", "0");
            DictionaryBaysOccupation.Add("LINE8_Upper_29", "0");
            DictionaryBaysOccupation.Add("LINE8_Upper_31", "0");
            DictionaryBaysOccupation.Add("LINE8_Upper_33", "0");
            DictionaryBaysOccupation.Add("LINE8_Upper_35", "0");
            DictionaryBaysOccupation.Add("LINE8_Upper_37", "0");
            DictionaryBaysOccupation.Add("LINE8_Upper_39", "0");
            DictionaryBaysOccupation.Add("LINE8_Upper_49", "0");
            DictionaryBaysOccupation.Add("LINE8_Upper_51", "0");
            DictionaryBaysOccupation.Add("LINE8_Upper_53", "0");
            DictionaryBaysOccupation.Add("LINE8_Upper_55", "0");
            DictionaryBaysOccupation.Add("LINE8_Upper_57", "0");
            DictionaryBaysOccupation.Add("LINE8_Upper_59", "0");
            DictionaryBaysOccupation.Add("LINE8_Upper_61", "0");
            DictionaryBaysOccupation.Add("LINE8_Upper_63", "0");
            DictionaryBaysOccupation.Add("LINE8_Upper_65", "0");
            DictionaryBaysOccupation.Add("LINE8_Upper_67", "0");
            DictionaryBaysOccupation.Add("LINE8_Upper_69", "0");
            DictionaryBaysOccupation.Add("LINE8_Upper_71", "0");
            DictionaryBaysOccupation.Add("LINEDMR_Lower_02", "0");
            DictionaryBaysOccupation.Add("LINEDMR_Lower_04", "0");
            DictionaryBaysOccupation.Add("LINEDMR_Lower_06", "0");
            DictionaryBaysOccupation.Add("LINEDMR_Lower_08", "0");
            DictionaryBaysOccupation.Add("LINEDMR_Lower_10", "0");
            DictionaryBaysOccupation.Add("LINEDMR_Lower_12", "0");
            DictionaryBaysOccupation.Add("LINEDMR_Lower_14", "0");
            DictionaryBaysOccupation.Add("LINEDMR_Lower_16", "0");
            DictionaryBaysOccupation.Add("LINEDMR_Upper_01", "0");
            DictionaryBaysOccupation.Add("LINEDMR_Upper_03", "0");
            DictionaryBaysOccupation.Add("LINEDMR_Upper_05", "0");
            DictionaryBaysOccupation.Add("LINEDMR_Upper_07", "0");
            DictionaryBaysOccupation.Add("LINEOBA_Lower_02", "0");
            DictionaryBaysOccupation.Add("LINEOBA_Lower_04", "0");
            DictionaryBaysOccupation.Add("LINEOBA_Lower_06", "0");
            DictionaryBaysOccupation.Add("LINEOBA_Lower_08", "0");
            DictionaryBaysOccupation.Add("LINEOBA_Lower_10", "0");
            DictionaryBaysOccupation.Add("LINEOBA_Lower_12", "0");
            DictionaryBaysOccupation.Add("LINEOBA_Lower_14", "0");
            DictionaryBaysOccupation.Add("LINEOBA_Lower_16", "0");
            DictionaryBaysOccupation.Add("LINEOBA_Upper_01", "0");
            DictionaryBaysOccupation.Add("LINEOBA_Upper_03", "0");
            DictionaryBaysOccupation.Add("LINEOBA_Upper_05", "0");
            DictionaryBaysOccupation.Add("LINEOBA_Upper_07", "0");
            DictionaryBaysOccupation.Add("LINEOBA_Upper_09", "0");
            DictionaryBaysOccupation.Add("LINEOBA_Upper_11", "0");
            DictionaryBaysOccupation.Add("LINEOBA_Upper_13", "0");
            DictionaryBaysOccupation.Add("LINEOBA_Upper_15", "0");
            DictionaryBaysOccupation.Add("LINEPRI_Lower_10", "0");
            DictionaryBaysOccupation.Add("LINEPRI_Lower_12", "0");
            DictionaryBaysOccupation.Add("LINEPRI_Lower_14", "0");
            DictionaryBaysOccupation.Add("LINEPRI_Lower_16", "0");
            DictionaryBaysOccupation.Add("LINEPRI_Lower_18", "0");
            DictionaryBaysOccupation.Add("LINEPRI_Lower_20", "0");
            DictionaryBaysOccupation.Add("LINEPRI_Lower_22", "0");
            DictionaryBaysOccupation.Add("LINEPRI_Lower_24", "0");
            DictionaryBaysOccupation.Add("LINEPRI_Upper_09", "0");
            DictionaryBaysOccupation.Add("LINEPRI_Upper_11", "0");
            DictionaryBaysOccupation.Add("LINEPRI_Upper_13", "0");
            DictionaryBaysOccupation.Add("LINEPRI_Upper_15", "0");
            DictionaryBaysOccupation.Add("LINEPRI_Upper_17", "0");
            DictionaryBaysOccupation.Add("LINEPRI_Upper_19", "0");
            DictionaryBaysOccupation.Add("LINEPRI_Upper_21", "0");
            DictionaryBaysOccupation.Add("LINEPRI_Upper_23", "0");

            return DictionaryBaysOccupation;
        }

        public static DataTable LoadDataTable_BayPositions()
        {
            List<string> ListBayPositions = LoadList_BayPositions();
            DataTable DataTableBaysOccupation = new DataTable();
            DataTableBaysOccupation.Clear();
            foreach (string bay in ListBayPositions)
            {
                DataTableBaysOccupation.Columns.Add(bay);
            }
            return DataTableBaysOccupation;
        }
    }
}
